config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from core.views import comics_views, ckeditor5_views

# from rhixe_scans.users import views as users_views
from django.conf.urls.i18n import i18n_patterns


urlpatterns = i18n_patterns(
    path(settings.ADMIN_URL, admin.site.urls),
    path(
        "",
        view=comics_views.index,
        name="index",
    ),
    path("comics/", include("core.urls.comics_urls")),
    path("bookmarks/", include("core.urls.usercomics_urls", namespace="bookmarks")),
    path("chapters/", include("core.urls.chapters_urls", namespace="chapters")),
    # Django Admin, use {% url 'admin:index' %}
    # User management
    path("users/", include("rhixe_scans.users.urls", namespace="users")),
    path("category/", include("core.urls.category_urls", namespace="category")),
    path("genre/", include("core.urls.genre_urls", namespace="genre")),
    path("artist/", include("core.urls.artist_urls", namespace="artist")),
    path("author/", include("core.urls.author_urls", namespace="author")),
    path(
        "progress/",
        view=comics_views.progress_view,
        name="progress",
    ),
    path(
        "task-status/<str:task_id>",
        comics_views.task_status,
        name="task_status",
    ),
    # path("ckeditor5/", include("django_ckeditor_5.urls")),
    path("ckeditor5/upload/", ckeditor5_views.upload_file, name="custom_upload_file"),
    # path("accounts/signup/", view=users_views.RegisterView.as_view()),
    # path("accounts/login/", view=users_views.LoginView.as_view()),
    path("accounts/", include("allauth.urls")),
    # path("accounts/", include("allauth.socialaccount.urls")),
    # path("accounts/", include("allauth.mfa.urls")),
    # path("accounts/", include("allauth.usersessions.urls")),
)

if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
else:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns
    if "django_browser_reload" in settings.INSTALLED_APPS:

        urlpatterns = [
            path("__reload__/", include("django_browser_reload.urls")),
        ] + urlpatterns

rhixe_scans/users/urls.py
from django.urls import path


from . import views

app_name = "users"

urlpatterns = [
    path("~redirect/", view=views.user_redirect_view, name="redirect"),
    path("~update/", view=views.user_update_view, name="update"),
    path("<int:pk>/", view=views.user_detail_view, name="detail"),
    path(
        "",
        view=views.user_list,
        name="list",
    ),
]

htmx_urlpatterns = [
    path(
        "<int:pk>/update/",
        view=views.user_edit,
        name="update-user",
    ),
    path(
        "<int:pk>/delete/",
        view=views.user_delete,
        name="delete-user",
    ),
    path("check-username/", views.check_username, name="check-username"),
    path("check-email/", views.check_email, name="check-email"),
]

urlpatterns += htmx_urlpatterns

rhixe_scans/users/models.py
from typing import ClassVar

from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.db.models import EmailField, BooleanField, ImageField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.core.validators import FileExtensionValidator
from .managers import UserManager


def user_image_location(instance, filename):
    return "{}/{}".format(
        str(instance.email)
        .replace(" ", "_")
        .replace(":", " ")
        .replace("/", "")
        .replace("\\", ""),
        filename,
    )


ext_validator = FileExtensionValidator(
    ["ico", "jpg", "svg", "jpeg", "png", "gif", "bmp", "webp", "tiff"]
)


class User(AbstractUser):
    """
    Default custom user model for Rhixe Scans.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    # name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = CharField(_("First Name of User"), blank=True, max_length=255)  # type: ignore[assignment]
    last_name = CharField(_("Last Name of User"), blank=True, max_length=255)  # type: ignore[assignment]
    email = EmailField(_("email address"), unique=True)
    username = CharField(_("User Name"), unique=True, max_length=2550)
    images = ImageField(
        _("Images"),
        upload_to=user_image_location,
        validators=[ext_validator],
        default="/images/user.png",
    )
    is_superuser = BooleanField(default=False)
    is_staff = BooleanField(default=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    objects: ClassVar[UserManager] = UserManager()

    def delete(self, *args, **kwargs):
        if self.images and self.images != "/images/user.png":
            self.images.delete()
        super().delete(*args, **kwargs)

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"pk": self.id})

    def update_absolute_url(self) -> str:
        return reverse("users:update-user", kwargs={"pk": self.id})

    def delete_absolute_url(self) -> str:
        return reverse("users:delete-user", kwargs={"pk": self.id})

core/views/chapters_views.py
from django_tables2 import RequestConfig
from core.decorators import admin_only, user_only
from core.forms import ChapterForm, NewCommentForm
from core.models import Chapter, Comment, Panel
from core.tables import ChapterTable
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, HttpResponseRedirect
from django.views.decorators.http import require_http_methods
from django_htmx.http import trigger_client_event, HttpResponseClientRefresh

from render_block import render_block_to_string
from core.filters import ChapterFilter

from django.conf import settings
from django_filters.views import FilterView
from django_tables2.views import SingleTableMixin
from django_tables2.export.export import TableExport
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse


@require_http_methods(["POST", "GET"])
@user_only
@admin_only
@login_required
def chapter_list(request):

    if request.method == "POST":
        form = ChapterForm(request.POST)
        if form.is_valid():
            chapter = form.save(commit=False)

            chapter.comic = form.cleaned_data["comic"]
            chapter.save()
            context = {"form": ChapterForm()}
        else:
            context = {"form": form}
        html = render_block_to_string(
            "partials/chapters/create.html", "Chapterscreate", context
        )
        response = HttpResponse(html)
        if form.is_valid():
            return trigger_client_event(response, "chapter_added")
            # return HttpResponseClientRefresh()
        return response

    chapters = Chapter.objects.all()
    myFilter = ChapterFilter(request.GET, queryset=chapters)
    table = ChapterTable(myFilter.qs)
    # table.paginate(page=request.GET.get("page", 1), per_page=settings.PAGINATE_BY)
    RequestConfig(request, paginate={"per_page": settings.PAGINATE_BY}).configure(table)
    export_format = request.GET.get("_export", None)
    if TableExport.is_valid_format(export_format):
        exporter = TableExport(export_format, table)
        return exporter.response(f"table.{export_format}")
    form = ChapterForm()
    export_formats = ["json"]
    context = {
        "table": table,
        "form": form,
        "filter": myFilter,
        "export_formats": export_formats,
    }

    if request.htmx:
        return render(request, "partials/chapters/table.html", context)

    return render(request, "core/chapters/admin.html", context)


@require_http_methods(["GET", "POST"])
@user_only
# @admin_only
@login_required
def chapter_detail(request, pk):
    chapter = get_object_or_404(Chapter, slug=pk)
    pagedata = Panel.objects.select_related("chapter").filter(
        chapter__slug=chapter.slug
    )
    allcomments = chapter.comment_chapter.all()
    page = request.GET.get("page", 1)

    paginator = Paginator(allcomments, settings.PAGINATE_BY)
    try:
        comments = paginator.page(page)
    except PageNotAnInteger:
        comments = paginator.page(1)
    except EmptyPage:
        comments = paginator.page(paginator.num_pages)

    if request.method == "POST":
        comment_form = NewCommentForm(request.POST)
        if comment_form.is_valid():

            comment = comment_form.save(commit=False)

            comment.user = request.user
            comment.chapter = Chapter.objects.get(slug=pk)
            comment.save()

            return HttpResponseRedirect("/chapters/" + pk)
    else:
        comment_form = NewCommentForm()

    context = {
        "chapter": chapter,
        "pages": pagedata,
        "comments": comments,
        "comment_form": comment_form,
        "allcomments": allcomments,
    }

    return render(request, "core/chapters/chapter.html", context)


@require_http_methods(["GET", "POST"])
@user_only
@login_required
def chapter_edit(request, pk):
    chapter = get_object_or_404(Chapter, id=pk)
    if request.method == "POST":
        form = ChapterForm(request.POST, instance=chapter)
        if form.is_valid():
            newchapter = form.save(commit=False)

            newchapter.comic = form.cleaned_data["comic"]
            newchapter.save()
            context = {
                "record": chapter,
                "chapter": chapter,
                "form": ChapterForm(instance=chapter),
            }
        else:
            context = {"record": chapter, "chapter": chapter, "form": form}

        html = render_block_to_string(
            "partials/chapters/update_button.html", "Chaptersupdate", context
        )
        response = HttpResponse(html)
        if form.is_valid():
            # return trigger_client_event(response, "chapter_added")
            return HttpResponseClientRefresh()
        return response
    form = ChapterForm(instance=chapter)
    context = {"record": chapter, "chapter": chapter, "form": form}
    html = render_block_to_string(
        "partials/chapters/update_button.html", "Chaptersupdate", context
    )
    return HttpResponse(html)


@require_http_methods(["DELETE"])
@admin_only
@login_required
def chapter_delete(request, pk):
    if Chapter.objects.filter(id=pk).exists():
        chapter = get_object_or_404(Chapter, id=pk)

        chapter.delete()

        response = HttpResponse("")

        return trigger_client_event(response, "chapter_added")
        # return HttpResponseClientRefresh()

rhixe_scans/templates/partials/chapters/create.html
{% load static i18n widget_tweaks crispy_forms_tags tailwind_filters %}
<!-- ChaptersCreate -->
{% block Chapterscreate %}

<button
  type="button"
  id="modalButton"
  class="text-white bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 dark:bg-primary-600 dark:hover:bg-primary-700 focus:outline-none dark:focus:ring-primary-800"
  _="on click add .hidden to #modalButton then remove .hidden from #modalEl"
>

  Add new chapter
</button>
<div
  id="modalEl"
  tabindex="-1"
  aria-hidden="true"
  class="{% if not form.errors %} fixed left-0 right-0 top-0 z-50  h-[calc(100%-1rem)] max-h-full w-full overflow-y-auto overflow-x-hidden p-4 md:inset-0 hidden {% else %} fixed left-0 right-0 top-0 z-50  h-[calc(100%-1rem)] max-h-full w-full overflow-y-auto overflow-x-hidden p-4 md:inset-0{% endif %} "
>
  <div class="relative max-h-full w-full max-w-2xl">
    <!-- Modal content -->
    <div class="relative rounded-lg bg-white shadow dark:bg-gray-700">
      <!-- Modal header -->
      <div class="flex items-start justify-between rounded-t border-b p-5 dark:border-gray-600">
        <h3 class="text-xl font-semibold text-gray-900 dark:text-white lg:text-2xl">Create Chapter</h3>
        <button
          type="button"
          id="modalButtonClose"
          class="ms-auto inline-flex h-8 w-8 items-center justify-center rounded-lg bg-transparent text-sm text-gray-400 hover:bg-gray-200 hover:text-gray-900 dark:hover:bg-gray-600 dark:hover:text-white"
          _="on click remove .hidden from #modalButton then add .hidden to #modalEl then put '' into <textarea />'s value then put '' into <input />'s value then put '' into <select />'s value"
        >
          <svg class="h-3 w-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
          </svg>
          <span class="sr-only">Close modal</span>
        </button>
      </div>
      <form
        hx-post="{% url 'chapters:list' %}"
        hx-encoding="multipart/form-data"
        hx-target="#modalEl"
        hx-indicator=".progress"
        class="max-w-sm mx-auto"
        _="on chapter_added remove .hidden from #modalButton then add .hidden to #modalEl then put '' into <textarea />'s value then put '' into <input />'s value then put '' into <select />'s value"
      >
        {% for hidden_field in form.hidden_fields %}
        <!-- for -->
        {{ hidden_field.errors }} {{ hidden_field }}
        <!-- endfor -->
        {% endfor %}

        {% for field in form %}


        <div class="mb-5">

          <label for="{{field.id}}" class="form-label">{{field.label}}</label>
          {% render_field field  %}
          <div class="mt-1 text-sm text-gray-500 dark:text-gray-300" id="chapter_{{field.name}}_help">{{ field.help_text }}</div>
          <div class="ml-3 text-xs text-red-400">{{ field.errors }}</div>
        </div>



        {% endfor %}
         <!-- non form errors -->
         {{ form.non_form_errors }}
        <!-- Modal footer -->
        <div class="flex flex-row justify-between items-center space-x-2 rounded-b border-t border-gray-200 p-6 dark:border-gray-600 rtl:space-x-reverse">
          <button
            type="submit"
            class="rounded-lg bg-blue-700 px-5 py-2.5 text-center text-sm font-medium text-white hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
          >
            Add new chapter
          </button>
          <button
            type="button"
            _="on click remove .hidden from #modalButton then add .hidden to #modalEl then put '' into <textarea />'s value then put '' into <input />'s value then put '' into <select />'s value"
            class="rounded-lg border border-gray-200 bg-white px-5 py-2.5 text-sm font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-900 focus:z-10 focus:outline-none focus:ring-4 focus:ring-blue-300 dark:border-gray-500 dark:bg-gray-700 dark:text-gray-300 dark:hover:bg-gray-600 dark:hover:text-white"
          >
            Cancel
          </button>
        </div>
      </form>
      <!-- Modal body -->
    </div>
  </div>
</div>

{% endblock Chapterscreate %}

rhixe_scans/templates/partials/chapters/delete_button.html
<!-- Modal toggle -->
<div class="flex justify-center">
  <button
    id="deleteButton-{{record.id}}"
    class="flex items-center rounded-lg bg-red-600 px-1 py-1 text-center text-sm font-medium text-white hover:bg-red-800 focus:ring-4 focus:ring-red-300 dark:focus:ring-red-900"
    type="button"
    _="on click add .hidden to #deleteButton-{{record.id}} then remove .hidden from #deleteModal-{{record.id}}"
  >
    <svg class="mr-2 h-4 w-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
      <path
        fill-rule="evenodd"
        d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z"
        clip-rule="evenodd"
      ></path>
    </svg>

  </button>
</div>

<!-- Main modal -->
<div
  id="deleteModal-{{record.id}}"
  tabindex="-1"
  aria-hidden="true"
  class="fixed left-0 right-0 top-0 z-50 hidden h-modal w-full items-center justify-center overflow-y-auto overflow-x-hidden md:inset-0 md:h-full"
>
  <div class="relative h-full w-full max-w-md p-4 md:h-auto">
    <!-- Modal content -->
    <div class="relative rounded-lg bg-white p-4 text-center shadow dark:bg-gray-800 sm:p-5">
      <button
        type="button"
        class="absolute right-2.5 top-2.5 ml-auto inline-flex items-center rounded-lg bg-transparent p-1.5 text-sm text-gray-400 hover:bg-gray-200 hover:text-gray-900 dark:hover:bg-gray-600 dark:hover:text-white"
        _="on click remove .hidden from #deleteButton-{{record.id}} then add .hidden to #deleteModal-{{record.id}}"
      >
        <svg aria-hidden="true" class="h-5 w-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path
            fill-rule="evenodd"
            d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
            clip-rule="evenodd"
          ></path>
        </svg>
        <span class="sr-only">Close modal</span>
      </button>
      <svg class="mx-auto mb-3.5 h-11 w-11 text-gray-400 dark:text-gray-500" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
        <path
          fill-rule="evenodd"
          d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z"
          clip-rule="evenodd"
        ></path>
      </svg>
      <p class="mb-4 text-gray-500 dark:text-gray-300">Are you sure you want to delete this item?</p>
      <div class="flex items-center justify-center space-x-4" _="on chapter_added remove .hidden from #deleteButton-{{record.id}} then add .hidden to #deleteModal-{{record.id}}">
        <button
          type="button"
          _="on click remove .hidden from #deleteButton-{{record.id}} then add .hidden to #deleteModal-{{record.id}}"
          class="rounded-lg border border-gray-200 bg-white px-1 py-1 text-sm font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-900 focus:z-10 focus:outline-none focus:ring-4 focus:ring-primary-300 dark:border-gray-500 dark:bg-gray-700 dark:text-gray-300 dark:hover:bg-gray-600 dark:hover:text-white dark:focus:ring-gray-600"
        >
          No, cancel
        </button>
        <button
          type="submit"
          hx-delete="{% url 'chapters:delete-chapter' record.id %}"
          hx-confirm="are you sure you want to delete {{record.title}}"
          hx-indicator=".progress"
          class="rounded-lg bg-red-600 px-1 py-1 text-center text-sm font-medium text-white hover:bg-red-700 focus:outline-none focus:ring-4 focus:ring-red-300 dark:bg-red-500 dark:hover:bg-red-600 dark:focus:ring-red-900"
        >
          Yes, I'm sure
        </button>
      </div>
    </div>
  </div>
</div>

rhixe_scans/templates/partials/chapters/django_tables2.html
{% load django_tables2 static i18n widget_tweaks component_tags %}
<!-- table -->
{% component "table" table=table %} {% endcomponent %}

<div
class="sticky bottom-0 right-0 flex w-full flex-row items-center justify-between gap-2 border-t border-b border-gray-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-800"
>
{% include 'partials/chapters/pagination.html' %}
</div>

rhixe_scans/templates/partials/chapters/pagination.html
{% load django_tables2 static i18n widget_tweaks %}
<!-- bj -->
{% block pagination %}
<!-- if table.pagintor -->

{% if table.page and table.paginator.num_pages > 1 %}
<div class="mb-4 flex items-center sm:mb-0">
  <button
    hx-get="{% querystring table.prefixed_page_field=1 %}"
    hx-target="#chapter-container"
    hx-indicator=".progress"
    hx-push-url="true"
    class="inline-flex cursor-pointer justify-center rounded p-1 text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:hover:bg-gray-700 dark:hover:text-white"
  >
    <svg class="h-7 w-7" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd"></path>
    </svg>
  </button>
  <button
    hx-get="{% querystring table.prefixed_page_field=table.paginator.num_pages %}"
    hx-target="#chapter-container"
    hx-indicator=".progress"
    hx-push-url="true"
    class="mr-2 inline-flex cursor-pointer justify-center rounded p-1 text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:hover:bg-gray-700 dark:hover:text-white"
  >
    <svg class="h-7 w-7" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path>
    </svg>
  </button>

  <span class="text-sm font-normal text-gray-500 dark:text-gray-400"
    >Showing <span class="font-semibold text-gray-900 dark:text-white">{{table.page.number}}</span> of
    <span class="font-semibold text-gray-900 dark:text-white">{{table.paginator.num_pages}}</span></span
  >
</div>
<ul class="flex h-8 items-center -space-x-px text-sm">
  {% if table.page.has_previous %}
  <li>
    <button
      hx-get="{% querystring table.prefixed_page_field=table.page.previous_page_number %}"
      hx-target="#chapter-container"
      hx-indicator=".progress"
      hx-push-url="true"
      class="ml-0 flex h-full items-center justify-center rounded-l-lg border border-gray-300 bg-white px-3 py-1.5 text-gray-500 hover:bg-gray-100 hover:text-gray-700 dark:border-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white"
    >
      <span class="sr-only">Previous</span>
      <svg class="h-5 w-5" aria-hidden="true" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd" />
      </svg>
    </button>
  </li>

  {% endif %}
  <!-- if -->
  {% for page_number in table.paginator.get_elided_page_range %}
  <!-- page number -->
  {% if page_number == table.paginator.ELLIPSIS %}
  <li>
    <button
      class="flex h-8 items-center justify-center border border-gray-300 bg-white px-3 leading-tight text-gray-500 hover:bg-gray-100 hover:text-gray-700 dark:border-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white"
    >
      {{page_number}}
    </button>
  </li>
  {% else %}
  <li>
    <button
    {% if page_number == table.page.number %}
      aria-current="page"
      {% endif %}
      class="z-10 flex items-center justify-center px-3 h-8 leading-tight border border-blue-300 dark:border-gray-700 {% if page_number == table.page.number %}  text-blue-600  bg-blue-50 hover:bg-blue-100 hover:text-blue-700  dark:bg-gray-700 dark:text-white {% else %}  text-gray-500 bg-white  hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800  dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white {% endif %}"
      hx-get="{% querystring table.prefixed_page_field=page_number %}"
      hx-target="#chapter-container"
      hx-indicator=".progress"
      hx-push-url="true"
    >
      {{page_number}}
    </button>
  </li>
  {% endif %}
  <!-- fgh -->
  {% endfor %}
  <!-- as -->
  {% if table.page.has_next %}
  <li>
    <button
      hx-get="{% querystring table.prefixed_page_field=table.page.next_page_number %}"
      hx-target="#chapter-container"
      hx-push-url="true"
      class="flex h-full items-center justify-center rounded-r-lg border border-gray-300 bg-white px-3 py-1.5 leading-tight text-gray-500 hover:bg-gray-100 hover:text-gray-700 dark:border-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white"
    >
      <span class="sr-only">Next</span>
      <svg class="h-5 w-5" aria-hidden="true" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
      </svg>
    </button>
  </li>

  {% endif %}
</ul>
{% endif %} {% endblock pagination %}

rhixe_scans/templates/partials/chapters/table.html
{% load render_table from django_tables2 %}
<!-- block chapterslist -->
<div class="progress">
  <div class="indeterminate"></div>
</div>

<div class="overflow-x-auto">
  {% block Chapterslist %}

  <div
    class="inline-block min-w-full align-middle"
    id="chapter-container"
    hx-trigger="chapter_added    from:body"
    hx-get='{% url "chapters:list" %}'
    hx-target="#chapter-container"
    hx-indicator=".progress"
  >
    {% render_table table "partials/chapters/django_tables2.html" %}
  </div>
  {% endblock Chapterslist %}
</div>