config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from core.views import comics_views, ckeditor5_views

# from rhixe_scans.users import views as users_views
from django.conf.urls.i18n import i18n_patterns


urlpatterns = i18n_patterns(
    path(settings.ADMIN_URL, admin.site.urls),
    path(
        "",
        view=comics_views.index,
        name="index",
    ),
    path("comics/", include("core.urls.comics_urls")),
    path("bookmarks/", include("core.urls.usercomics_urls", namespace="bookmarks")),
    path("chapters/", include("core.urls.chapters_urls", namespace="chapters")),
    # Django Admin, use {% url 'admin:index' %}
    # User management
    path("users/", include("rhixe_scans.users.urls", namespace="users")),
    path("category/", include("core.urls.category_urls", namespace="category")),
    path("genre/", include("core.urls.genre_urls", namespace="genre")),
    path("artist/", include("core.urls.artist_urls", namespace="artist")),
    path("author/", include("core.urls.author_urls", namespace="author")),
    path(
        "progress/",
        view=comics_views.progress_view,
        name="progress",
    ),
    path(
        "task-status/<str:task_id>",
        comics_views.task_status,
        name="task_status",
    ),
    # path("ckeditor5/", include("django_ckeditor_5.urls")),
    path("ckeditor5/upload/", ckeditor5_views.upload_file, name="custom_upload_file"),
    # path("accounts/signup/", view=users_views.RegisterView.as_view()),
    # path("accounts/login/", view=users_views.LoginView.as_view()),
    path("accounts/", include("allauth.urls")),
    # path("accounts/", include("allauth.socialaccount.urls")),
    # path("accounts/", include("allauth.mfa.urls")),
    # path("accounts/", include("allauth.usersessions.urls")),
)

if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
else:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns
    if "django_browser_reload" in settings.INSTALLED_APPS:

        urlpatterns = [
            path("__reload__/", include("django_browser_reload.urls")),
        ] + urlpatterns

rhixe_scans/users/urls.py
from django.urls import path


from . import views

app_name = "users"

urlpatterns = [
    path("~redirect/", view=views.user_redirect_view, name="redirect"),
    path("~update/", view=views.user_update_view, name="update"),
    path("<int:pk>/", view=views.user_detail_view, name="detail"),
    path(
        "",
        view=views.user_list,
        name="list",
    ),
]

htmx_urlpatterns = [
    path(
        "<int:pk>/update/",
        view=views.user_edit,
        name="update-user",
    ),
    path(
        "<int:pk>/delete/",
        view=views.user_delete,
        name="delete-user",
    ),
    path("check-username/", views.check_username, name="check-username"),
    path("check-email/", views.check_email, name="check-email"),
]

urlpatterns += htmx_urlpatterns

rhixe_scans/users/models.py
from typing import ClassVar

from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.db.models import EmailField, BooleanField, ImageField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.core.validators import FileExtensionValidator
from .managers import UserManager


def user_image_location(instance, filename):
    return "{}/{}".format(
        str(instance.email)
        .replace(" ", "_")
        .replace(":", " ")
        .replace("/", "")
        .replace("\\", ""),
        filename,
    )


ext_validator = FileExtensionValidator(
    ["ico", "jpg", "svg", "jpeg", "png", "gif", "bmp", "webp", "tiff"]
)


class User(AbstractUser):
    """
    Default custom user model for Rhixe Scans.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    # name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = CharField(_("First Name of User"), blank=True, max_length=255)  # type: ignore[assignment]
    last_name = CharField(_("Last Name of User"), blank=True, max_length=255)  # type: ignore[assignment]
    email = EmailField(_("email address"), unique=True)
    username = CharField(_("User Name"), unique=True, max_length=2550)
    images = ImageField(
        _("Images"),
        upload_to=user_image_location,
        validators=[ext_validator],
        default="/images/user.png",
    )
    is_superuser = BooleanField(default=False)
    is_staff = BooleanField(default=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    objects: ClassVar[UserManager] = UserManager()

    def delete(self, *args, **kwargs):
        if self.images and self.images != "/images/user.png":
            self.images.delete()
        super().delete(*args, **kwargs)

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"pk": self.id})

    def update_absolute_url(self) -> str:
        return reverse("users:update-user", kwargs={"pk": self.id})

    def delete_absolute_url(self) -> str:
        return reverse("users:delete-user", kwargs={"pk": self.id})

rhixe_scans/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView
from django.views.generic import RedirectView
from django.views.generic import UpdateView
from core.decorators import admin_only, user_only
from rhixe_scans.users.forms import UserForm, UserAdminForm
from rhixe_scans.users.models import User
from core.tables import UserTable
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.views.decorators.http import require_http_methods
from django_htmx.http import trigger_client_event, HttpResponseClientRefresh
from render_block import render_block_to_string
from core.filters import UserFilter
from django_filters.views import FilterView
from django_tables2.views import SingleTableMixin
from allauth.account.views import LoginView, SignupView
from django_tables2.export import ExportMixin
from django_tables2.export.export import TableExport
from django.conf import settings
from django_tables2 import RequestConfig
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView


def avatar(request):
    if request.user.is_authenticated:
        user = User.objects.get(email=request.user)

        avatar = User.objects.filter(email=user)

        context = {
            "avatar": avatar,
        }
        return context
    else:
        return {"NotLoggedIn": User.objects.none()}


def check_username(request):
    username = request.POST.get("username")

    if User.objects.filter(username=username).exists():
        return HttpResponse(
            " <div class='myerror mt-4' x-data='{ dismissed:false }' x-show='!dismissed' x-init='setTimeout(() =>  dismissed=true, 10000)'><div id='toast'class='mb-4 flex w-full max-w-md items-center rounded-lg bg-white p-4 text-gray-500 shadow dark:bg-gray-800 dark:text-gray-400'role='alert'><div  class='error'><svg class='h-5 w-5' aria-hidden='true' xmlns='http://www.w3.org/2000/svg' fill='currentColor' viewBox='0 0 20 20'><path d='M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 11.793a1 1 0 1 1-1.414 1.414L10 11.414l-2.293 2.293a1 1 0 0 1-1.414-1.414L8.586 10 6.293 7.707a1 1 0 0 1 1.414-1.414L10 8.586l2.293-2.293a1 1 0 0 1 1.414 1.414L11.414 10l2.293 2.293Z' /></svg><span class='sr-only'>Error icon</span></div><div class='ml-3 text-sm font-normal'>This username already exists</div><button @click='dismissed=true' type='button'class='-mx-1.5 -my-1.5 ml-auto inline-flex h-8 w-8 items-center justify-center rounded-lg bg-white p-1.5 text-gray-400 hover:bg-gray-100 hover:text-gray-900 focus:ring-2 focus:ring-gray-300 dark:bg-gray-800 dark:text-gray-500 dark:hover:bg-gray-700 dark:hover:text-white'data-dismiss-target='#toast' aria-label='Close'><span class='sr-only'>Close</span><svg class='h-3 w-3' aria-hidden='true' xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 14 14'><path stroke='currentColor' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6' /></svg></button></div></div>"
        )
    else:
        return HttpResponse(
            "<div class='mysuccess    mt-4' x-data='{ dismissed:false }' x-show='!dismissed' x-init='setTimeout(() =>  dismissed=true, 10000)'><div id='toast'class='mb-4 flex w-full max-w-md items-center rounded-lg bg-white p-4 text-gray-500 shadow dark:bg-gray-800 dark:text-gray-400'role='alert'><div class='success' ><svg class='h-5 w-5' aria-hidden='true' xmlns='http://www.w3.org/2000/svg' fill='currentColor' viewBox='0 0 20 20'><path d='M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z' /></svg><span class='sr-only'>Check icon</span></div><div class='ml-3 text-sm font-normal'>This username is available</div><button @click='dismissed=true' type='button' class='-mx-1.5 -my-1.5 ml-auto inline-flex h-8 w-8 items-center justify-center rounded-lg bg-white p-1.5 text-gray-400 hover:bg-gray-100 hover:text-gray-900 focus:ring-2 focus:ring-gray-300 dark:bg-gray-800 dark:text-gray-500 dark:hover:bg-gray-700 dark:hover:text-white' data-dismiss-target='#toast' aria-label='Close'><span class='sr-only'>Close</span><svg class='h-3 w-3' aria-hidden='true' xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 14 14'><path stroke='currentColor' stroke-linecap='round' stroke-linejoin='round' stroke-width='2'd='m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6' /></svg></button></div></div>"
        )


def check_email(request):
    email = request.POST.get("email")
    if User.objects.filter(email=email).exists():
        return HttpResponse(
            " <div class='myerror mt-4' x-data='{ dismissed:false }' x-show='!dismissed' x-init='setTimeout(() =>  dismissed=true, 10000)'><div id='toast'class='mb-4 flex w-full max-w-md items-center rounded-lg bg-white p-4 text-gray-500 shadow dark:bg-gray-800 dark:text-gray-400'role='alert'><div  class='error'><svg class='h-5 w-5' aria-hidden='true' xmlns='http://www.w3.org/2000/svg' fill='currentColor' viewBox='0 0 20 20'><path d='M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 11.793a1 1 0 1 1-1.414 1.414L10 11.414l-2.293 2.293a1 1 0 0 1-1.414-1.414L8.586 10 6.293 7.707a1 1 0 0 1 1.414-1.414L10 8.586l2.293-2.293a1 1 0 0 1 1.414 1.414L11.414 10l2.293 2.293Z' /></svg><span class='sr-only'>Error icon</span></div><div class='ml-3 text-sm font-normal'>This email already exists</div><button @click='dismissed=true' type='button'class='-mx-1.5 -my-1.5 ml-auto inline-flex h-8 w-8 items-center justify-center rounded-lg bg-white p-1.5 text-gray-400 hover:bg-gray-100 hover:text-gray-900 focus:ring-2 focus:ring-gray-300 dark:bg-gray-800 dark:text-gray-500 dark:hover:bg-gray-700 dark:hover:text-white'data-dismiss-target='#toast' aria-label='Close'><span class='sr-only'>Close</span><svg class='h-3 w-3' aria-hidden='true' xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 14 14'><path stroke='currentColor' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6' /></svg></button></div></div>"
        )
    else:
        return HttpResponse(
            "<div class='mysuccess    mt-4' x-data='{ dismissed:false }' x-show='!dismissed' x-init='setTimeout(() =>  dismissed=true, 10000)'><div id='toast'class='mb-4 flex w-full max-w-md items-center rounded-lg bg-white p-4 text-gray-500 shadow dark:bg-gray-800 dark:text-gray-400'role='alert'><div class='success' ><svg class='h-5 w-5' aria-hidden='true' xmlns='http://www.w3.org/2000/svg' fill='currentColor' viewBox='0 0 20 20'><path d='M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z' /></svg><span class='sr-only'>Check icon</span></div><div class='ml-3 text-sm font-normal'>This email is available</div><button @click='dismissed=true' type='button' class='-mx-1.5 -my-1.5 ml-auto inline-flex h-8 w-8 items-center justify-center rounded-lg bg-white p-1.5 text-gray-400 hover:bg-gray-100 hover:text-gray-900 focus:ring-2 focus:ring-gray-300 dark:bg-gray-800 dark:text-gray-500 dark:hover:bg-gray-700 dark:hover:text-white' data-dismiss-target='#toast' aria-label='Close'><span class='sr-only'>Close</span><svg class='h-3 w-3' aria-hidden='true' xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 14 14'><path stroke='currentColor' stroke-linecap='round' stroke-linejoin='round' stroke-width='2'd='m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6' /></svg></button></div></div>"
        )


@require_http_methods(["POST", "GET"])
@user_only
@admin_only
@login_required
def user_list(request):

    if request.method == "POST":
        form = UserForm(request.POST, request.FILES)
        if form.is_valid():

            email = form.cleaned_data["email"]
            username = form.cleaned_data["username"]
            password1 = form.cleaned_data["password1"]
            images = form.cleaned_data["images"]
            User.objects.create_superuser(
                email=email, username=username, images=images, password=password1
            )

            context = {"form": UserForm()}
        else:
            context = {"form": form}
        html = render_block_to_string(
            "partials/users/create.html", "Userscreate", context
        )
        response = HttpResponse(html)
        if form.is_valid():
            return trigger_client_event(response, "user_added")
            # return HttpResponseClientRefresh()
        return response

    users = User.objects.all()
    myFilter = UserFilter(request.GET, queryset=users)
    table = UserTable(myFilter.qs)
    # table.paginate(page=request.GET.get("page", 1), per_page=settings.PAGINATE_BY)
    RequestConfig(request, paginate={"per_page": settings.PAGINATE_BY}).configure(table)
    export_format = request.GET.get("_export", None)
    if TableExport.is_valid_format(export_format):
        exporter = TableExport(export_format, table)
        return exporter.response(f"table.{export_format}")
    form = UserForm()
    export_formats = ["json"]
    context = {
        "table": table,
        "form": form,
        "filter": myFilter,
        "export_formats": export_formats,
    }

    if request.htmx:
        return render(request, "partials/users/table.html", context)

    return render(request, "users/admin.html", context)


class Login(LoginView):
    template_name = "account/login.html"


class RegisterView(SignupView):
    template_name = "account/signup.html"
    # form_class = UserSignupForm

    # def form_valid(self, form):
    #     email = form.cleaned_data["email"]

rhixe_scans/templates/partials/users/button.html
{% block bookmarkComic %}
<div id="bookmark-container" class="mt-6 sm:mt-8 sm:flex sm:items-center sm:gap-4">
  {% if request.user in comic.users.all %}
  <button
    class="flex items-center justify-center rounded-lg border border-gray-200 bg-white px-5 py-2.5 text-sm font-medium text-gray-900 hover:bg-gray-100 hover:text-primary-700 focus:z-10 focus:outline-none focus:ring-4 focus:ring-gray-100 dark:border-gray-600 dark:bg-gray-800 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white dark:focus:ring-gray-700"
    type="button"
    hx-delete="{% url 'bookmarks:delete-comic' comic.pk %}"
    hx-confirm="Are you sure you wish to delete?"
    hx-target="#bookmark-container"
  >
    <i class="fa-regular fa-bookmark -ms-2 me-2 h-5 w-5"></i>

    Remove favorites
  </button>

  {% else %}
  <button
    class="flex items-center justify-center rounded-lg border border-gray-200 bg-white px-5 py-2.5 text-sm font-medium text-gray-900 hover:bg-gray-100 hover:text-primary-700 focus:z-10 focus:outline-none focus:ring-4 focus:ring-gray-100 dark:border-gray-600 dark:bg-gray-800 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white dark:focus:ring-gray-700"
    type="button"
    hx-post="{% url 'bookmarks:add-comic' %}"
    hx-vals='{"comictitle": "{{comic.title}}"}'
    hx-trigger="click"
    hx-target="#bookmark-container"
  >
    <svg class="-ms-2 me-2 h-5 w-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12.01 6.001C6.5 1 1 8 5.782 13.001L12.011 20l6.23-7C23 8 17.5 1 12.01 6.002Z" />
    </svg>
    Add to bookmarks
  </button>
  {% endif %}
</div>
{% endblock bookmarkComic %}

rhixe_scans/templates/partials/users/create.html
{% load static i18n widget_tweaks crispy_forms_tags tailwind_filters %}
<!-- UsersCreate -->
{% block Userscreate %}

<button
  type="button"
  id="modalButton"
  class="flex items-center justify-center rounded-lg bg-primary-700 px-4 py-2 text-sm font-medium text-white hover:bg-primary-800 focus:outline-none focus:ring-4 focus:ring-primary-300 dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800"
  _="on click add .hidden to #modalButton then remove .hidden from #modalEl"
>
  <svg class="mr-2 h-3.5 w-3.5" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
    <path clip-rule="evenodd" fill-rule="evenodd" d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" />
  </svg>
  Add user
</button>
<div
  id="modalEl"
  tabindex="-1"
  aria-hidden="true"
  class="{% if not form.errors %} {% endif %} fixed left-0 right-0 top-0 z-50 hidden h-[calc(100%-1rem)] max-h-full w-full overflow-y-auto overflow-x-hidden p-4 md:inset-0"
>
  <div class="relative max-h-full w-full max-w-2xl">
    <!-- Modal content -->
    <div class="relative rounded-lg bg-white shadow dark:bg-gray-700">
      <!-- Modal header -->
      <div class="flex items-start justify-between rounded-t border-b p-5 dark:border-gray-600">
        <h3 class="text-xl font-semibold text-gray-900 dark:text-white lg:text-2xl">Create User</h3>
        <button
          type="button"
          id="modalButtonClose"
          class="ms-auto inline-flex h-8 w-8 items-center justify-center rounded-lg bg-transparent text-sm text-gray-400 hover:bg-gray-200 hover:text-gray-900 dark:hover:bg-gray-600 dark:hover:text-white"
          _="on click remove .hidden from #modalButton then add .hidden to #modalEl then put '' into <textarea />'s value then put '' into <input />'s value then put '' into <select />'s value"
        >
          <svg class="h-3 w-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
          </svg>
          <span class="sr-only">Close modal</span>
        </button>
      </div>
      <form
        hx-post="{% url 'users:list' %}"
        hx-encoding="multipart/form-data"
        _="on user_added remove .hidden from #modalButton then add .hidden to #modalEl then put '' into <textarea />'s value then put '' into <input />'s value then put '' into <select />'s value"
      >
        <div class="space-y-4 p-4">
          <div>
            <div class="grid grid-cols-6 gap-6">
              <div class="col-span-6 sm:col-span-3">
                {{ form.email|add_label_class:"form-label" }}
                <!-- email input -->
                {% render_field form.email %}
                <span class="ml-3 text-sm text-gray-400"> {{ form.email.help_text }} </span>
                <div class="ml-3 text-xs text-red-400">{{ form.email.errors }}</div>
              </div>
              <div class="col-span-6 sm:col-span-3">
                {{ form.username|add_label_class:"form-label" }}
                <!-- username input -->
                {% render_field form.username %}
                <span class="ml-3 text-sm text-gray-400"> {{ form.username.help_text }} </span>
                <div class="ml-3 text-xs text-red-400">{{ form.username.errors }}</div>
              </div>

              <div class="col-span-6">
                {{ form.images|add_label_class:"form-label" }}
                <!-- images input -->
                {% render_field form.images class="form-files" %}
                <span class="ml-3 text-sm text-gray-400"> {{ form.images.help_text }} </span>
                <div class="ml-3 text-xs text-red-400">{{ form.images.errors }}</div>
              </div>

              <div class="col-span-6 sm:col-span-3">
                {{ form.password1|add_label_class:"form-label" }}
                <!-- password1 input -->
                {% render_field form.password1 %}
                <span class="ml-3 text-sm text-gray-400"> {{ form.password1.help_text }} </span>
                <div class="ml-3 text-xs text-red-400">{{ form.password1.errors }}</div>
              </div>
              <div class="col-span-6 sm:col-span-3">
                {{ form.password2|add_label_class:"form-label" }}
                <!-- password2 input -->
                {% render_field form.password2 %}
                <span class="ml-3 text-sm text-gray-400"> {{ form.password2.help_text }} </span>
                <div class="ml-3 text-xs text-red-400">{{ form.password2.errors }}</div>
              </div>
              <div class="col-span-6">
                {{ form.captcha|add_label_class:"form-label" }}
                <!-- captcha input -->
                {% render_field form.captcha %}
                <span class="ml-3 text-sm text-gray-400"> {{ form.captcha.help_text }} </span>
                <div class="ml-3 text-xs text-red-400">{{ form.captcha.errors }}</div>
              </div>
            </div>
          </div>
        </div>
        <!-- Modal footer -->
        <div class="flex items-center space-x-2 rounded-b border-t border-gray-200 p-6 dark:border-gray-600 rtl:space-x-reverse">
          <button
            type="submit"
            class="rounded-lg bg-blue-700 px-5 py-2.5 text-center text-sm font-medium text-white hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
          >
            Create
          </button>
          <button
            type="button"
            class="rounded-lg border border-gray-200 bg-white px-5 py-2.5 text-sm font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-900 focus:z-10 focus:outline-none focus:ring-4 focus:ring-blue-300 dark:border-gray-500 dark:bg-gray-700 dark:text-gray-300 dark:hover:bg-gray-600 dark:hover:text-white"
          >
            Decline
          </button>
        </div>
      </form>
      <!-- Modal body -->
    </div>
  </div>
</div>

{% endblock Userscreate %}

rhixe_scans/templates/partials/users/django_tables2.html
{% load django_tables2 static i18n widget_tweaks component_tags %}
<!-- table -->
{% component "table" table=table %} {% endcomponent %}
<!-- pagination -->
{% include 'partials/users/pagination.html' %}

rhixe_scans/templates/partials/users/table.html
{% load static i18n widget_tweaks humanize%}
<!-- block userslist -->
{% block Userslist %}
<!-- Define Grid container div -->
{% load render_table from django_tables2 %}

<div id="user-container" hx-trigger="user_added    from:body" hx-get='{% url "users:list" %}' hx-target="#user-container">{% render_table table "partials/users/django_tables2.html" %}</div>
{% endblock Userslist %}